version: "3"
services:
  file-code-box:
    build:
      context: .
      dockerfile: Dockerfile
    image: ruida/filecodebox:latest
    container_name: filecodebox
    volumes:
      - /root/apps/.filecodebox:/app/data:rw
    restart: unless-stopped
    ports:
      - "3006:12345"